const dia12pt = [
  {
    finish: '18h00',
    id: 1,
    start: '16h00',
    title: 'Recepção, credenciamento e atividades de conexão',
    local: ['Recepção'],
  },
  {
    finish: '19h00',
    id: 2,
    start: '18h00',
    title: 'Abertura do FICOO 2023',
    local: ['Quadra 2'],
  },
  {
    finish: '20h30',
    id: 3,
    start: '19h00',
    title:
      'Conferência I: May East - 1001 formas de regenerar as alianças afetivas entre a humanidade e todos sistemas vivos',
    local: ['Teatro'],
  },
  {
    finish: '21h30',
    id: 4,
    start: '20h30',
    title: 'O Desafio FICOO: Edgard Gouveia Jr',
    local: ['Quadra 2'],
  },
];
export const dia13pt = [
  {
    finish: '09h00',
    id: 1,
    start: '08h30',
    title: 'Atividades de conexão',
    local: ['Quadra 2 '],
  },
  {
    finish: '10h30',
    id: 2,
    start: '09h00',
    title:
      'Painel Colaborativo 1: Helena Marujo, Fábio Eon, Maria Paula e Michelle Confessor - Cultura de Paz e Saúde Integral na Educação',
    local: ['Teatro'],
  },
  {
    finish: '11h00',
    id: 3,
    start: '10h30',
    title: 'Tempo livre e Mercado Colaborativo',
  },
  {
    finish: '13h00',
    id: 4,
    start: '11h00',
    title: 'Rodas de ConversAção:',
    local: ['Comunidade: sala 2E', 'Meio ambiente: sala 2C'],
  },
  {
    finish: '13h00',
    id: 5,
    start: '11h00',
    title: 'Laboratório de Com-Vivências:',
    local: [
      '1. Heloisa Biscaia: sala 1D',
      '2. Edson e Marisa Passos: sala 2A',
      '3. Carol Silva e Claudia Prado: sala 1A',
      '4. Leonardo Dutra Guedes: sala de apoio 4',
      '5. Cláudio Casaccia: sala 8A',
      '6. Danielle Rangel: sala de apoio 1',
      '7. Jane Fontana: lab aprend. 2',
      '8. Lairton Martins: sala 3A',
      '9. Paulo Vinícius: sala de música',
    ],
  },
  {
    finish: '14h30',
    id: 6,
    start: '13h00',
    title: 'Tempo livre e Mercado Colaborativo',
  },
  {
    finish: '18h30',
    id: 7,
    start: '14h30',
    title: 'Oficinas de Cooperação',
    local: [
      '1. Isabela Crema: sala 2E',
      '2. Ita Gabert: sala 2C',
      '3. André Korsakas: sala 1D',
      '4. Fred Magalhães: sala de Música',
      '5. Marcelo Castilho: sala de apoio 4',
      '6. Rodrigo Xavier: sala 3C',
      '7. Renata Nogueira: sala 2A',
      '8. Marco Aurélio Bilibio: sala de apoio 1',
      '9. Felipe, Magda e Letícia: sala de apoio 2',
      '10. Roberto Martini: sala 3A',
    ],
  },
  {
    finish: '19h00',
    id: 8,
    start: '18h30',
    title: 'Tempo livre e Mercado Colaborativo',
  },
  {
    finish: '20h30',
    id: 9,
    start: '19h00',
    title:
      'Painel Colaborativo 2: Marcos Sorrentino, Caçadores de Bons Exemplos e Wilson Nobre - Boas Práticas Colaborativas em Inovação Social, Desenvolvimento Pessoal e Regeneração Ambiental',
    local: ['Teatro'],
  },
  {
    finish: '22h00',
    id: 10,
    start: '20h30',
    title: 'A Comum-Unidade FICOO: Cine Fusca Trevo e Time do Coração',
    local: ['Pátio verde'],
  },
];
export const dia14pt = [
  {
    finish: '09h00',
    id: 1,
    start: '08h30',
    title: 'Atividades de conexão',
    local: ['Quadra 2'],
  },
  {
    finish: '10h30',
    id: 2,
    start: '09h00',
    title:
      'Conferência II: Daniel Wahl com a facilitação de Ivy Frizo - Cultura Regenerativa e Sociedade Colaborativa',
    local: ['Teatro'],
  },
  {
    finish: '11h00',
    id: 3,
    start: '10h30',
    title: 'Tempo livre e Mercado Colaborativo',
  },
  {
    finish: '13h00',
    id: 4,
    start: '11h00',
    title: 'Rodas de ConversAção:',
    local: ['Relações de Gênero - sala 2E', 'Trabalho em Equipe - sala 2C'],
  },
  {
    finish: '13h00',
    id: 5,
    start: '11h00',
    title: 'Laboratório de Com-Vivências:',
    local: [
      '10. Denise Cavalcanti: sala 1D',
      '11. Roberto Olivella e Maria Salette: sala 2A',
      '12. Renata Moraes: sala 1A',
      '13. Roberta Schwartz: sala de apoio 4',
      '14. Inês Salles e Renata Codagan: sala 8A',
      '15. Paulo Henrique e Raquel Flores: sala de apoio 1',
      '16. Maria Clara de Castro: lab aprend. 2',
      '17. Elaine Queiroz: sala 3A',
      '18. Izadora Barros: sala de música',
    ],
  },
  {
    finish: '14h30',
    id: 6,
    start: '13h00',
    title: 'Tempo livre e Mercado Colaborativo',
  },
  {
    finish: '18h00',
    id: 7,
    start: '14h30',
    title: 'Oficinas de Cooperação:',
    local: [
      '1. Isabela Crema: sala 2E',
      '2. Ita Gabert: sala 2C',
      '3. André Korsakas: sala 1D',
      '4. Fred Magalhães: sala de Música',
      '5. Marcelo Castilho: sala de apoio 4',
      '6. Rodrigo Xavier: sala 3C',
      '7. Renata Nogueira: sala 2A',
      '8. Marco Aurélio Bilibio: sala de apoio 1',
      '9. Felipe, Magda e Letícia: sala de apoio 2',
      '10. Roberto Martini: sala 3A',
    ],
  },
  {
    finish: '19h00',
    id: 8,
    start: '18h30',
    title: 'Tempo livre e Mercado Colaborativo',
  },
  {
    finish: '20h30',
    id: 9,
    start: '19h00',
    title: 'A Grande Síntese: Lydia Rebouças',
    local: ['Teatro'],
  },
  {
    finish: '22h00',
    id: 10,
    start: '20h30',
    title: 'Festa DIVER e Encerramento do Festival',
    local: ['Quadra 2'],
  },
];

export const dia12es = [
  {
    finish: '18h00',
    id: 1,
    start: '16h00',
    title: 'Recepción, acreditación y actividades de conexión',
    local: ['Recepción'],
  },
  {
    finish: '19h00',
    id: 2,
    start: '18h00',
    title: 'Apertura de FICOO 2023',
    local: ['Patio 2'],
  },
  {
    finish: '20h30',
    id: 3,
    start: '19h00',
    title:
      'Conferencia 1: MAY EAST - 1001 formas de regenerar las alianzas emocionales entre la humanidad y todos los sistemas vivos',
    local: ['Teatro'],
  },
  {
    finish: '21h30',
    id: 4,
    start: '20h30',
    title: 'El Desafío FICOO: Edgard Gouveia Jr',
    local: ['Patio 2'],
  },
];
export const dia13es = [
  {
    finish: '09h00',
    id: 1,
    start: '08h30',
    title: 'Actividades de conexión',
    local: ['Patio 2'],
  },
  {
    finish: '10h30',
    id: 2,
    start: '09h00',
    title:
      'Panel Colaborativo 1: Helena Marujo, Fábio Eon, Maria Paula y Michelle Confessor - Cultura de Paz y Salud Integral en la Educación',

    local: ['Teatro'],
  },
  {
    finish: '11h00',
    id: 3,
    start: '10h30',
    title: 'Tiempo libre y Mercado Colaborativo',
  },
  {
    finish: '13h00',
    id: 4,
    start: '11h00',
    title: 'Círculos de ConversAcción',
    local: ['Comunidad: sala 2E', 'Medio ambiente: sala 2C'],
  },
  {
    finish: '13h00',
    id: 5,
    start: '11h00',
    title: 'Laboratorio de Co-Vivencias:',
    local: [
      '1. Heloisa Biscaia: sala 1D',
      '2. Edson y Marisa Passos: sala 2A',
      '3. Carol Silva e Claudia Prado: sala 1A',
      '4. Leonardo Dutra Guedes: sala de apoyo 4',
      '5. Cláudio Casaccia: sala 8A',
      '6. Danielle Rangel: sala de apoyo 1',
      '7. Jane Fontana: lab de aprend. 2',
      '8. Lairton Martins: sala 3A',
      '9. Paulo Vinícius: salón de música',
    ],
  },
  {
    finish: '14h30',
    id: 6,
    start: '13h00',
    title: 'Tiempo libre y Mercado Colaborativo',
  },
  {
    finish: '18h30',
    id: 7,
    start: '14h30',
    title: 'Talleres de Cooperación',
    local: [
      '1. Isabela Crema: sala 2E',
      '2. Ita Gabert: sala 2C',
      '3. André Korsakas: sala 1D',
      '4. Fred Magalhães: salón de música',
      '5. Marcelo Castilho: sala de apoyo 4',
      '6. Rodrigo Xavier: sala 3C',
      '7. Renata Nogueira: sala 2A',
      '8. Marco Aurélio Bilibio: sala de apoyo 1',
      '9. Felipe, Magda y Letícia: sala de apoyo 2',
      '10. Roberto Martini: sala 3A',
    ],
  },
  {
    finish: '19h00',
    id: 8,
    start: '18h30',
    title: 'Tiempo libre y Mercado Colaborativo',
  },
  {
    finish: '20h30',
    id: 9,
    start: '19h00',
    title:
      'Panel Colaborativo 2: Marcos Sorrentino, Cazadores de Buenos Ejemplos y Wilson Nobre - Buenas Prácticas Colaborativas en Innovación Social, Desarrollo Personal y Regeneración Ambiental.',
    local: ['Teatro'],
  },
  {
    finish: '22h00',
    id: 10,
    start: '20h30',
    title: 'La Unidad Común-FICOO: Cine Fusca Trevo y Heart Team',
    local: ['Patio verde'],
  },
];
export const dia14es = [
  {
    finish: '09h00',
    id: 1,
    start: '08h30',
    title: 'Actividades de conexión',
    local: ['Patio 2'],
  },
  {
    finish: '10h30',
    id: 2,
    start: '09h00',
    title:
      'Conferencia II: Daniel Wahl facilitada por Ivy Frizo - Cultura Regenerativa y Sociedad Colaborativa',

    local: ['Teatro'],
  },
  {
    finish: '11h00',
    id: 3,
    start: '10h30',
    title: 'Tiempo libre y Mercado Colaborativo',
  },
  {
    finish: '13h00',
    id: 4,
    start: '11h00',
    title: 'Círculos de ConversAcción:',
    local: ['Relaciones de género - sala 2E', 'Trabajo en equipo - sala 2C'],
  },
  {
    finish: '13h00',
    id: 5,
    start: '11h00',
    title: 'Laboratorio de Co-Vivencias:',
    local: [
      '10. Denise Cavalcanti: sala 1D',
      '11. Roberto Olivella y Maria Salette: sala 2A',
      '12. Renata Moraes: sala 1A',
      '13. Roberta Schwartz: sala de apoyo 4',
      '14. Inês Salles y Renata Codagan: sala 8A',
      '15. Paulo Henrique y Raquel Flores: sala de apoyo 1',
      '16. Maria Clara de Castro: laboratorio de aprendizaje 2',
      '17. Elaine Queiroz: sala 3A',
      '18. Izadora Barros: salón de música',
    ],
  },
  {
    finish: '14h30',
    id: 6,
    start: '13h00',
    title: 'Tiempo libre y Mercado Colaborativo',
  },
  {
    finish: '18h00',
    id: 7,
    start: '14h30',
    title: 'Talleres de Cooperación',
    local: [
      '1. Isabela Crema: sala 2E',
      '2. Ita Gabert: sala 2C',
      '3. André Korsakas: sala 1D',
      '4. Fred Magalhães: salón de música',
      '5. Marcelo Castilho: sala de apoyo 4',
      '6. Rodrigo Xavier: sala 3C',
      '7. Renata Nogueira: sala 2A',
      '8. Marco Aurélio Bilibio: sala de apoyo 1',
      '9. Felipe, Magda y Letícia: sala de apoyo 2',
      '10. Roberto Martini: sala 3A',
    ],
  },
  {
    finish: '19h00',
    id: 8,
    start: '18h30',
    title: 'Tiempo libre y Mercado Colaborativo',
  },
  {
    finish: '20h30',
    id: 9,
    start: '19h00',
    title: 'La Gran Síntesis: Lydia Rebouças',
    local: ['Teatro'],
  },
  {
    finish: '22h00',
    id: 10,
    start: '20h30',
    title: 'Fiesta DIVER y Cierre del Festival',
    local: ['Patio 2'],
  },
];

export const dia12en = [
  {
    finish: '18h00',
    id: 1,
    start: '16h00',
    title: 'Reception, accreditation, and connection activities',
    local: ['Reception'],
  },
  {
    finish: '19h00',
    id: 2,
    start: '18h00',
    title: 'Opening of FICOO 2023',
    local: ['Quadra 2'],
  },
  {
    finish: '20h30',
    id: 3,
    start: '19h00',
    title:
      'Conference I: May East - 1001 ways to regenerate affective alliances between humanity and all living systems',

    local: ['theater'],
  },
  {
    finish: '21h30',
    id: 4,
    start: '20h30',
    title: 'The FICOO Challenge: Edgard Gouveia Jr',
    local: ['Quadra 2'],
  },
];
export const dia13en = [
  {
    finish: '09h00',
    id: 1,
    start: '08h30',
    title: 'Connection activities',
    local: ['Quadra 2'],
  },
  {
    finish: '10h30',
    id: 2,
    start: '09h00',
    title:
      'Collaborative Panel 1: Helena Marujo, Fábio Eon, Maria Paula and Michelle Confessor - Culture of Peace and Integral Health in Education',
    local: ['Theater'],
  },
  {
    finish: '11h00',
    id: 3,
    start: '10h30',
    title: 'Free time and Collaborative Market',
  },
  {
    finish: '13h00',
    id: 4,
    start: '11h00',
    title: 'ConversAction Circles',
    local: ['Community: room 2E', 'Environment: room 2C'],
  },
  {
    finish: '13h00',
    id: 5,
    start: '11h00',
    title: 'Com-Living Lab:',
    local: [
      '1. Heloisa Biscaia: room 1D',
      '2. Edson and Marisa Passos: room 2A',
      '3. Carol Silva e Claudia Prado: room 1A',
      '4. Leonardo Dutra Guedes: support room 4',
      '5. Cláudio Casaccia: room 8A',
      '6. Danielle Rangel: support room 1',
      '7. Jane Fontana: learning lab 2',
      '8. Lairton Martins: 3A room',
      '9. Paulo Vinícius: music room',
    ],
  },
  {
    finish: '14h30',
    id: 6,
    start: '13h00',
    title: 'Free time and Collaborative Market',
  },
  {
    finish: '18h30',
    id: 7,
    start: '14h30',
    title: 'Cooperation Workshops',
    local: [
      '1. Isabela Crema: room 2E',
      '2. Ita Gabert: room 2C',
      '3. André Korsakas: room 1D',
      '4. Fred Magalhães: music room',
      '5. Marcelo Castilho: support room 4',
      '6. Rodrigo Xavier: room 3C',
      '7. Renata Nogueira: room 2A',
      '8. Marco Aurélio Bilibio: support room 1',
      '9. Felipe, Magda and Letícia: support room 2',
      '10. Roberto Martini: 3A room',
    ],
  },
  {
    finish: '19h00',
    id: 8,
    start: '18h30',
    title: 'Free time and Collaborative Market',
  },
  {
    finish: '20h30',
    id: 9,
    start: '19h00',
    title:
      'Collaborative Panel 2: Marcos Sorrentino, Hunters of Good Examples and Wilson Nobre - Collaborative Good Practices in Social Innovation, Personal Development and Environmental Regeneration',
    local: ['Theater'],
  },
  {
    finish: '22h00',
    id: 10,
    start: '20h30',
    title: 'The Common-FICOO Unit: Cine Fusca Trevo and Heart Team',
    local: ['Green patio'],
  },
];
export const dia14en = [
  {
    finish: '09h00',
    id: 1,
    start: '08h30',
    title: 'Connection activities',
    local: ['Quadra 2'],
  },
  {
    finish: '10h30',
    id: 2,
    start: '09h00',
    title:
      'Conference II: Daniel Wahl facilitated by Ivy Frizo - Regenerative Culture and Collaborative Society',
    local: ['Theater'],
  },
  {
    finish: '11h00',
    id: 3,
    start: '10h30',
    title: 'Free time and Collaborative Market',
  },
  {
    finish: '13h00',
    id: 4,
    start: '11h00',
    title: 'ConversAction Circles',
    local: ['Gender Relations - room 2E', 'Teamwork - room 2C'],
  },
  {
    finish: '13h00',
    id: 5,
    start: '11h00',
    title: 'Com-Living Lab:',
    local: [
      '10. Denise Cavalcanti: room 1D',
      '11. Roberto Olivella and Maria Salette: room 2A',
      '12. Renata Moraes: room 1A',
      '13. Roberta Schwartz: support room 4',
      '14. Inês Salles and Renata Codagan: room 8A',
      '15. Paulo Henrique and Raquel Flores: support room 1',
      '16. Maria Clara de Castro: learning lab 2',
      '17. Elaine Queiroz: 3A room',
      '18. Izadora Barros: music room',
    ],
  },
  {
    finish: '14h30',
    id: 6,
    start: '13h00',
    title: 'Free time and Collaborative Market',
  },
  {
    finish: '18h00',
    id: 7,
    start: '14h30',
    title: 'Cooperation Workshops:',
    local: [
      '1. Isabela Crema: room 2E',
      '2. Ita Gabert: room 2C',
      '3. André Korsakas: room 1D',
      '4. Fred Magalhães: music room',
      '5. Marcelo Castilho: support room 4',
      '6. Rodrigo Xavier: room 3C',
      '7. Renata Nogueira: room 2A',
      '8. Marco Aurélio Bilibio: support room 1',
      '9. Felipe, Magda and Letícia: support room 2',
      '10. Roberto Martini: 3A room',
    ],
  },
  {
    finish: '19h00',
    id: 8,
    start: '18h30',
    title: 'Free time and Collaborative Market',
  },
  {
    finish: '20h30',
    id: 9,
    start: '19h00',
    title: 'The Great Synthesis: Lydia Rebouças',
    local: ['Theater'],
  },
  {
    finish: '22h00',
    id: 10,
    start: '20h30',
    title: 'DIVER Party and Festival Closing',
    local: ['Quadra 2'],
  },
];

export const list = {
  dia12pt: dia12pt,
  dia12en: dia12en,
  dia12es: dia12es,
  dia13pt: dia13pt,
  dia13en: dia13en,
  dia13es: dia13es,
  dia14pt: dia14pt,
  dia14en: dia14en,
  dia14es: dia14es,
};
